<a href="https://colab.research.google.com/github/maciekbanas/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello')

Hello


In [ ]:
pip install numpy

In [3]:
import numpy as np

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(10,8),fill_value = 7, dtype='int')

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [ ]:
np.arange(start = 5, stop = 100, step = 9)

array([ 5, 14, 23, 32, 41, 50, 59, 68, 77, 86, 95])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x = np.full(shape = (5,5), fill_value = 3)
y = np.full(shape = (5,5), fill_value = 2)
x @ y
print(x, '\n', y)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]] 
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [ ]:
np.random.randn()

-0.1959780700103187

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([4, 0, 2, 1, 3, 9, 7, 8, 6, 5])

In [ ]:
bool(0)

False

In [ ]:
x = np.array([2,3,4])

In [ ]:
print(x)

[2 3 4]


In [4]:
x = np.array([np.random.randint(low=10,high=100,size=8),np.random.randint(low=10,high=100,size=8)])
print(x)

[[78 89 31 18 57 91 78 55]
 [71 29 15 77 59 83 75 86]]


In [11]:
for row in x:
  print(row)

[78 89 31 18 57 91 78 55]
[71 29 15 77 59 83 75 86]


In [13]:
for item in x.flat:
  print(item)

78
89
31
18
57
91
78
55
71
29
15
77
59
83
75
86


In [14]:
x.T

array([[78, 71],
       [89, 29],
       [31, 15],
       [18, 77],
       [57, 59],
       [91, 83],
       [78, 75],
       [55, 86]])

In [17]:
x > 70

array([[ True,  True, False, False, False,  True,  True, False],
       [ True, False, False,  True, False,  True,  True,  True]])

In [18]:
x[x > 50]

array([78, 89, 57, 91, 78, 55, 71, 77, 59, 83, 75, 86])

In [19]:
np.bitwise_and(x > 50, x < 90)

array([[ True,  True, False, False,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True,  True,  True]])