<a href="https://colab.research.google.com/github/maciekbanas/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
v1 = np.array([-1,4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

In [ ]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, "\n")
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X,Y)
print(Z)

[[ 2]
 [-6]]


In [ ]:
Z.shape

(2, 1)

In [ ]:
np.set_printoptions(4,suppress=True)

In [3]:
import numpy as np
A = np.array([[2, 4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [5]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [7]:
A_inv = np.linalg.inv(A)
X =  np.dot(A_inv,B)
X

array([[1.],
       [2.]])

In [8]:
X.shape

(2, 1)