<a href="https://colab.research.google.com/github/maciekbanas/data-science-bootcamp/blob/main/kurs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello')

Hello


In [2]:
pip install numpy

In [3]:
import numpy as np

In [6]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full(shape=(10,8),fill_value = 7, dtype='int')

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [13]:
np.arange(start = 5, stop = 100, step = 9)

array([ 5, 14, 23, 32, 41, 50, 59, 68, 77, 86, 95])

In [17]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
x = np.full(shape = (5,5), fill_value = 3)
y = np.full(shape = (5,5), fill_value = 2)
x @ y
print(x, '\n', y)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]] 
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [29]:
np.random.randn()

-0.1959780700103187

In [32]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.random.shuffle(data)

In [34]:
data

array([4, 0, 2, 1, 3, 9, 7, 8, 6, 5])

In [36]:
bool(0)

False

In [38]:
x = np.array([2,3,4])

In [39]:
print(x)

[2 3 4]


In [45]:
x = np.array([np.random.randint(low=10,high=100,size=8),np.random.randint(low=10,high=100,size=8)])
print(x)

[[39 10 46 77 35 89 77 91]
 [59 82 15 39 24 47 68 22]]
